#include <iostream>
#include <vector>
#include <fstream>
#include <complex>
#include <thread>
#include <chrono>

class MandelbrotGenerator {
private:
    const int width, height;
    const int max_iterations;
    const double escape_radius;
    
public:
    MandelbrotGenerator(int n, int max_iter = 1000) 
        : width(n), height(n), max_iterations(max_iter), escape_radius(2.0) {}
    
    // Check if a point belongs to Mandelbrot set using quadratic recurrence
    int mandelbrot_point(std::complex<double> c) {
        std::complex<double> z(0.0, 0.0);  // z_0 = 0
        int iterations = 0;
        
        while (std::abs(z) <= escape_radius && iterations < max_iterations) {
            z = z * z + c;  // z_{n+1} = z_n^2 + c
            iterations++;
        }
        
        return iterations;
    }
    
    // Generate Mandelbrot set data
    std::vector<std::vector<int>> generate_mandelbrot(double x_min = -2.0, double x_max = 1.0, 
                                                     double y_min = -1.5, double y_max = 1.5) {
        std::vector<std::vector<int>> image(height, std::vector<int>(width));
        
        double x_step = (x_max - x_min) / width;
        double y_step = (y_max - y_min) / height;
        
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                std::complex<double> c(x_min + x * x_step, y_min + y * y_step);
                image[y][x] = mandelbrot_point(c);
            }
        }
        
        return image;
    }
    
    // Threaded version for better performance
    std::vector<std::vector<int>> generate_mandelbrot_threaded(double x_min = -2.0, double x_max = 1.0,
                                                              double y_min = -1.5, double y_max = 1.5) {
        std::vector<std::vector<int>> image(height, std::vector<int>(width));
        unsigned int num_threads = std::thread::hardware_concurrency();
        if (num_threads == 0) num_threads = 4; // Fallback
        
        std::vector<std::thread> threads;
        int rows_per_thread = height / num_threads;
        
        for (unsigned int t = 0; t < num_threads; ++t) {
            int start_row = t * rows_per_thread;
            int end_row = (t == num_threads - 1) ? height : (t + 1) * rows_per_thread;
            
            threads.emplace_back([&, start_row, end_row, x_min, x_max, y_min, y_max]() {
                double x_step = (x_max - x_min) / width;
                double y_step = (y_max - y_min) / height;
                
                for (int y = start_row; y < end_row; ++y) {
                    for (int x = 0; x < width; ++x) {
                        std::complex<double> c(x_min + x * x_step, y_min + y * y_step);
                        image[y][x] = mandelbrot_point(c);
                    }
                }
            });
        }
        
        for (auto& thread : threads) {
            thread.join();
        }
        
        return image;
    }
    
    // Convert iteration count to PBM pixel (1 for in set, 0 for out of set)
    bool iteration_to_pixel(int iterations) {
        return iterations == max_iterations;
    }
    
    // Save as PBM (Portable Bitmap) format
    void save_as_pbm(const std::vector<std::vector<int>>& image, const std::string& filename) {
        std::ofstream file(filename, std::ios::binary);
        if (!file) {
            std::cerr << "Error opening file: " << filename << std::endl;
            return;
        }
        
        // PBM header
        file << "P1\n";
        file << "# Mandelbrot Set - Generated by Quadratic Recurrence\n";
        file << width << " " << height << "\n";
        
        // Image data
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                file << (iteration_to_pixel(image[y][x]) ? "1 " : "0 ");
            }
            file << "\n";
        }
        
        file.close();
        std::cout << "Mandelbrot set saved as: " << filename << std::endl;
    }
    
    // Memory usage estimation
    void print_memory_usage(int n) {
        size_t image_memory = n * n * sizeof(int);
        size_t total_estimated = image_memory * 2; // Account for temporary objects
        
        std::cout << "Memory usage estimation:\n";
        std::cout << "  Image data: " << image_memory / (1024 * 1024) << " MB\n";
        std::cout << "  Total estimated: " << total_estimated / (1024 * 1024) << " MB\n";
        std::cout << "  Available RAM: 8192 MB\n";
        
        if (total_estimated > 6 * 1024 * 1024 * 1024ULL) { // 6GB threshold
            std::cout << "  WARNING: High memory usage detected!\n";
        }
    }
};

int main(int argc, char* argv[]) {
    // Configuration
    int N = 1000;  // Default size
    int max_iterations = 1000;
    bool use_threading = true;
    
    // Parse command line arguments
    if (argc > 1) {
        N = std::stoi(argv[1]);
        if (N <= 0) {
            std::cerr << "Invalid size. Using default N=1000" << std::endl;
            N = 1000;
        }
    }
    
    if (argc > 2) {
        max_iterations = std::stoi(argv[2]);
    }
    
    std::cout << "Generating Mandelbrot Set (" << N << "x" << N << ")\n";
    std::cout << "Max iterations: " << max_iterations << "\n";
    std::cout << "Using quadratic recurrence: z₀ = 0, zₙ₊₁ = zₙ² + C\n\n";
    
    MandelbrotGenerator generator(N, max_iterations);
    generator.print_memory_usage(N);
    
    auto start_time = std::chrono::high_resolution_clock::now();
    
    // Generate Mandelbrot set
    std::vector<std::vector<int>> mandelbrot_image;
    if (use_threading && N > 500) {
        std::cout << "\nUsing multi-threaded generation...\n";
        mandelbrot_image = generator.generate_mandelbrot_threaded();
    } else {
        std::cout << "\nUsing single-threaded generation...\n";
        mandelbrot_image = generator.generate_mandelbrot();
    }
    
    auto end_time = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time);
    
    std::cout << "Generation time: " << duration.count() << " ms\n";
    
    // Save as PBM
    std::string filename = "mandelbrot_" + std::to_string(N) + "x" + std::to_string(N) + ".pbm";
    generator.save_as_pbm(mandelbrot_image, filename);
    
    std::cout << "\nTo view the image, use:\n";
    std::cout << "  display " << filename << "          # ImageMagick\n";
    std::cout << "  xv " << filename << "               # XV viewer\n";
    std::cout << "  convert " << filename << " mandelbrot.png  # Convert to PNG\n";
    
    return 0;
}